# Generated by Django 4.2.3 on 2023-07-23 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0005_userlocationrank_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlocationrank",
            name="location",
        ),
        migrations.RemoveField(
            model_name="userlocationrank",
            name="user",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="UserLocationRank",
        ),
    ]
