# Generated by Django 4.2.3 on 2023-07-24 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0006_remove_userlocationrank_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="cover_charge",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("bar", "Bar"),
                    ("brewery", "Brewery"),
                    ("club", "Club"),
                    ("winebar", "Wine Bar"),
                    ("restaurant", "Restaurant"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MaxValueValidator(10.0)],
            ),
        ),
    ]
