# Generated by Django 4.2.3 on 2023-07-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0007_alter_location_cover_charge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("brewery", "Brewery"),
                            ("club", "Club"),
                            ("winebar", "Wine Bar"),
                            ("restaurant", "Restaurant"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="location",
            name="location_type",
        ),
        migrations.CreateModel(
            name="AffiliateAppURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="map_app.affiliateapp",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_urls",
                        to="map_app.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.ManyToManyField(to="map_app.locationtype"),
        ),
    ]
